### PR TITLE
fix(tests): Fixed quaternion unit tests

### PR DESCRIPTION
**Pull request by reinzor**
Fixes https://github.com/ethz-asl/kindr_ros/issues/16

### CODE REVIEW

**Comment by reinzor** [comment]
Ping

**Comment by remod** [comment]
lgtm, @pfankhauser ?

**Comment by pfankhauser** [comment]
Thanks @reinzor! I'd be happy to merge, could you quickly explain why you did this change? Did the unit tests not work for you?

**Comment by reinzor** [comment]
The unit tests were indeed failing due to the quaternion accuracy.

**Comment by pfankhauser** [comment]
Ok, not for us, weird. Thanks!

**Comment by reinzor** [comment]
I referred to the wrong issue, should close #14

**Pull request merged**
