### PR TITLE
Removed predefined color from vector at position

### PR DESCRIPTION
**Pull request by gehrinch**
If the colors are not predefined.Your can set it in rviz.

### CODE REVIEW

**Comment by remod** [comment]
Can you describe me the issue are you trying to solve? Where are the color predefinitions now?

**Comment by pfankhauser** [comment]
No fix, it's a feature! =)

**Comment by remod** [comment]
The only thing I see is removed code ;-)

**Comment by gehrinch** [comment]
I wanted to visualized desired and measured contact forces in different colors. In the code, the color red was always used when the type is force. This way, I couldn't change the color in rviz (in the properties).  The default color is now black as defined in the constructor and the user can define the color later in rviz. Does that make sense?

**Comment by remod** [comment]
Please check if this also works for you, then we can merge it! Thanks

**Comment by gehrinch** [comment]
lgtm

**Pull request merged**
